---
# Kevin M. Meziere <kmeziere@jpcatholic.com>
# Copyright 2015, John Paul the Great Catholic University

chunter_version_required: 0.7.1
chunter_release: rel
chunter_download_name: chunter-0.7.1.gz
chunter_cookie: <<chunter_cookie>>
