---
# Kevin M. Meziere <kmeziere@jpcatholic.com>
# Copyright 2015, John Paul the Great Catholic University

- name: Lookup version of Howl
  shell: "pkgin list | grep fifo-howl | awk -F'[;]' '{print $1}'"
  register: howl_version_installed
  changed_when: "howl_version_installed.stdout != '{{ howl_version_required }}'"
  ignore_errors: True

- include: install.yml
  when: "howl_version_installed.stdout != '{{ howl_version_required }}'"

- name: Configure Howl
  template: src=howl-config.j2 dest=/opt/local/fifo-howl/etc/howl.conf backup=yes
  notify: Bounce Howl

- name: Enable EPMD
  service: name=epmd state=started enabled=yes
  when: "'howl_no_start' not in {{ group_names }}"

- name: Enable Howl
  service: name=howl state=started enabled=yes
  when: "'howl_no_start' not in {{ group_names }}"
  register: howl_service_start

- name: Pause for Howl Startup
  pause: seconds=20
  when: howl_service_start.changed != False