---
# Kevin M. Meziere <kmeziere@jpcatholic.com>
# Copyright 2015, John Paul the Great Catholic University

- name: Bounce Howl
  service: name=howl state=restarted enabled=yes
  when: "'howl_no_start' not in {{ group_names }}"