---
# Kevin M. Meziere <kmeziere@jpcatholic.com>
# Copyright 2015, John Paul the Great Catholic University

- name: Bounce Sniffle
  service: name=sniffle state=restarted enabled=yes
  when: "'sniffle_no_start' not in {{ group_names }}"